version: '3.8'

services:
  mongodb-local:
    container_name: mongodb-local
    image: "mongo:3.6.8"
    restart: always
    env_file:
      - .env.mongodb
    ports:
      - 27017:27017
    networks:
      - products_network
    volumes:
      - ./resources/database/products-db-master/database/01-products.json:/database/01-products.json
      - mongodb:/data/db
    command: [--auth]

  mongo-seed:
    container_name: mongo-seed
    build:
      dockerfile: dockerfile.mongodb-seed
      context: ./resources/database/products-db-master/database
    env_file:
      - .env.mongodb
    networks:
      - products_network
    depends_on:
      - mongodb-local

  backend_products:
    build:
      dockerfile: dockerfile.backend-products
      context: .
    ports:
      - 8082:8082
    volumes:
      - .:/walmart-products
    env_file:
      - .env.products
    depends_on:
      - mongodb_products
    networks:
      - products_network

networks:
  products_network:
    driver: bridge

volumes:
  mongodb: