// Code generated by MockGen. DO NOT EDIT.
// Source: productService.go

// Package services is a generated GoMock package.
package services

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	response "github.com/yescorihuela/walmart-products/app/response"
	errs "github.com/yescorihuela/walmart-products/errs"
)

// MockProductService is a mock of ProductService interface.
type MockProductService struct {
	ctrl     *gomock.Controller
	recorder *MockProductServiceMockRecorder
}

// MockProductServiceMockRecorder is the mock recorder for MockProductService.
type MockProductServiceMockRecorder struct {
	mock *MockProductService
}

// NewMockProductService creates a new mock instance.
func NewMockProductService(ctrl *gomock.Controller) *MockProductService {
	mock := &MockProductService{ctrl: ctrl}
	mock.recorder = &MockProductServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductService) EXPECT() *MockProductServiceMockRecorder {
	return m.recorder
}

// FindAllProducts mocks base method.
func (m *MockProductService) FindAllProducts() ([]response.ProductResponse, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllProducts")
	ret0, _ := ret[0].([]response.ProductResponse)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// FindAllProducts indicates an expected call of FindAllProducts.
func (mr *MockProductServiceMockRecorder) FindAllProducts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllProducts", reflect.TypeOf((*MockProductService)(nil).FindAllProducts))
}

// FindProductsByCriteria mocks base method.
func (m *MockProductService) FindProductsByCriteria(arg0 string) ([]response.ProductResponse, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProductsByCriteria", arg0)
	ret0, _ := ret[0].([]response.ProductResponse)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// FindProductsByCriteria indicates an expected call of FindProductsByCriteria.
func (mr *MockProductServiceMockRecorder) FindProductsByCriteria(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProductsByCriteria", reflect.TypeOf((*MockProductService)(nil).FindProductsByCriteria), arg0)
}
