// Code generated by MockGen. DO NOT EDIT.
// Source: product.go

// Package domain is a generated GoMock package.
package domain

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/yescorihuela/walmart-products/domain"
	errs "github.com/yescorihuela/walmart-products/errs"
)

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// GetAllProducts mocks base method.
func (m *MockProductRepository) GetAllProducts() ([]domain.Product, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProducts")
	ret0, _ := ret[0].([]domain.Product)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// GetAllProducts indicates an expected call of GetAllProducts.
func (mr *MockProductRepositoryMockRecorder) GetAllProducts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProducts", reflect.TypeOf((*MockProductRepository)(nil).GetAllProducts))
}

// GetProductsByCriteria mocks base method.
func (m *MockProductRepository) GetProductsByCriteria(arg0 string) ([]domain.Product, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsByCriteria", arg0)
	ret0, _ := ret[0].([]domain.Product)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// GetProductsByCriteria indicates an expected call of GetProductsByCriteria.
func (mr *MockProductRepositoryMockRecorder) GetProductsByCriteria(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsByCriteria", reflect.TypeOf((*MockProductRepository)(nil).GetProductsByCriteria), arg0)
}
